package cz.muni.stanse.gui;

@SuppressWarnings("serial")
final class ChooseCheckerDialog extends javax.swing.JDialog {

    // package-private section

    ChooseCheckerDialog() {
        super(MainWindow.getInstance(),true);
        initComponents();

        chooseCheckerManager = new ChooseCheckerManager(this,
                                        checkerNamesList,checkerInfoTextArea,
                                        chooseCheckerButton,cancelButton);
    }

    ChooseCheckerManager getChooseCheckerManager() {
        return chooseCheckerManager;
    }

    // private section

    private final ChooseCheckerManager chooseCheckerManager;

    //
    // Begin --- section generated by NetBeans - do not modify ! ---
    //
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checkerNamesScrollPane = new javax.swing.JScrollPane();
        checkerNamesList = new javax.swing.JList();
        checkerInfoScrollPane = new javax.swing.JScrollPane();
        checkerInfoTextArea = new javax.swing.JTextArea();
        chooseCheckerButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Checker selection");
        setResizable(false);

        checkerNamesList.setModel(new javax.swing.DefaultListModel());
        checkerNamesList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        checkerNamesScrollPane.setViewportView(checkerNamesList);

        checkerInfoTextArea.setColumns(20);
        checkerInfoTextArea.setEditable(false);
        checkerInfoTextArea.setLineWrap(true);
        checkerInfoTextArea.setRows(5);
        checkerInfoTextArea.setWrapStyleWord(true);
        checkerInfoTextArea.setFocusable(false);
        checkerInfoScrollPane.setViewportView(checkerInfoTextArea);

        chooseCheckerButton.setText("Choose");

        cancelButton.setText("Cancel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(checkerNamesScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
            .addComponent(checkerInfoScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(361, Short.MAX_VALUE)
                .addComponent(chooseCheckerButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancelButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(checkerNamesScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkerInfoScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chooseCheckerButton)
                    .addComponent(cancelButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JScrollPane checkerInfoScrollPane;
    private javax.swing.JTextArea checkerInfoTextArea;
    private javax.swing.JList checkerNamesList;
    private javax.swing.JScrollPane checkerNamesScrollPane;
    private javax.swing.JButton chooseCheckerButton;
    // End of variables declaration//GEN-END:variables
    //
    // End --- section generated by NetBeans - do not modify ! ---
    //
}
