package cz.muni.stanse.gui;

@SuppressWarnings("serial")
final class GuiConfigurationDialog extends javax.swing.JDialog {

    // package-private section

    GuiConfigurationDialog() {
        super(GuiMainWindow.getInstance(),true);

        initComponents();

        sourceConfigurationManager =
            new GuiSourceConfigurationManager(actualOpenedFileRadioButton,
                                              allOpenedFilesRadioButton,
                                              singleSourceFileRadioButton,
                                              makefileRadioButton,
                                              allDirectoryFilesRadioButton,
                                          allDirectoryHierarchyFilesRadioButton,
                                              batchFileRadioButton,
                                              sourceCodeFileTextField,
                                              chooseFileOnDiscButton);
        checkersConfurationManager =
            new GuiCheckersConfurationManager(checkersTree,addCheckerButton,
                            removeCheckerButton,addDataButton,removeDataButton);

        closeButton.addActionListener(new java.awt.event.ActionListener() {
            @Override public void actionPerformed(
                                           final java.awt.event.ActionEvent e) {
                setVisible(false);
                dispose();
            }
        });
    }

    GuiSourceConfigurationManager getSourceConfigurationManager() {
        return sourceConfigurationManager;
    }

    GuiCheckersConfurationManager getCheckersConfurationManager() {
        return checkersConfurationManager;
    }

    // private section

    private final GuiSourceConfigurationManager sourceConfigurationManager;
    private final GuiCheckersConfurationManager checkersConfurationManager;

    //
    // Begin --- section generated by NetBeans - do not modify ! ---
    //
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sourceTypeButtonGroup = new javax.swing.ButtonGroup();
        configurationTabbedPane = new javax.swing.JTabbedPane();
        sourceCodePanel = new javax.swing.JPanel();
        selectTypeStaticText = new javax.swing.JTextPane();
        actualOpenedFileRadioButton = new javax.swing.JRadioButton();
        allOpenedFilesRadioButton = new javax.swing.JRadioButton();
        singleSourceFileRadioButton = new javax.swing.JRadioButton();
        makefileRadioButton = new javax.swing.JRadioButton();
        allDirectoryFilesRadioButton = new javax.swing.JRadioButton();
        allDirectoryHierarchyFilesRadioButton = new javax.swing.JRadioButton();
        batchFileRadioButton = new javax.swing.JRadioButton();
        specifySourceFileStaticText = new javax.swing.JTextPane();
        sourceCodeFileTextField = new javax.swing.JTextField();
        chooseFileOnDiscButton = new javax.swing.JButton();
        checkersPanel = new javax.swing.JPanel();
        checkersTreeScrollPane = new javax.swing.JScrollPane();
        checkersTree = new javax.swing.JTree();
        addCheckerButton = new javax.swing.JButton();
        removeCheckerButton = new javax.swing.JButton();
        addDataButton = new javax.swing.JButton();
        removeDataButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Stanse configuration");
        setModal(true);
        setName("configurationDialog"); // NOI18N
        setResizable(false);

        selectTypeStaticText.setText("Select identification type of source file(s) to be checked:");
        selectTypeStaticText.setFocusable(false);

        sourceTypeButtonGroup.add(actualOpenedFileRadioButton);
        actualOpenedFileRadioButton.setText("Shown opened source file");
        actualOpenedFileRadioButton.setActionCommand("shown");

        sourceTypeButtonGroup.add(allOpenedFilesRadioButton);
        allOpenedFilesRadioButton.setText("All opened source files");
        allOpenedFilesRadioButton.setActionCommand("all");

        sourceTypeButtonGroup.add(singleSourceFileRadioButton);
        singleSourceFileRadioButton.setText("Single specific source file");
        singleSourceFileRadioButton.setActionCommand("single");

        sourceTypeButtonGroup.add(makefileRadioButton);
        makefileRadioButton.setText("Makefile project");
        makefileRadioButton.setActionCommand("makefile");

        sourceTypeButtonGroup.add(allDirectoryFilesRadioButton);
        allDirectoryFilesRadioButton.setText("All source code files in directory");

        sourceTypeButtonGroup.add(allDirectoryHierarchyFilesRadioButton);
        allDirectoryHierarchyFilesRadioButton.setText("All source code files in directory and subdirectories");

        sourceTypeButtonGroup.add(batchFileRadioButton);
        batchFileRadioButton.setText("All source code files in specified batch-file");

        specifySourceFileStaticText.setText("Path-name to source file, Makefile, batch file, or directory:");
        specifySourceFileStaticText.setFocusable(false);

        sourceCodeFileTextField.setToolTipText("Specify path-name to source code file, which should be checked for bugs.");

        chooseFileOnDiscButton.setText("Choose");

        javax.swing.GroupLayout sourceCodePanelLayout = new javax.swing.GroupLayout(sourceCodePanel);
        sourceCodePanel.setLayout(sourceCodePanelLayout);
        sourceCodePanelLayout.setHorizontalGroup(
            sourceCodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sourceCodePanelLayout.createSequentialGroup()
                .addGroup(sourceCodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sourceCodePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(selectTypeStaticText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(sourceCodePanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(sourceCodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(makefileRadioButton)
                            .addComponent(singleSourceFileRadioButton)
                            .addComponent(allOpenedFilesRadioButton)
                            .addComponent(actualOpenedFileRadioButton)
                            .addComponent(allDirectoryFilesRadioButton)
                            .addComponent(allDirectoryHierarchyFilesRadioButton)
                            .addComponent(batchFileRadioButton)))
                    .addGroup(sourceCodePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(sourceCodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(specifySourceFileStaticText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(sourceCodePanelLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(sourceCodeFileTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chooseFileOnDiscButton, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        sourceCodePanelLayout.setVerticalGroup(
            sourceCodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sourceCodePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selectTypeStaticText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(actualOpenedFileRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(allOpenedFilesRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(singleSourceFileRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(makefileRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(allDirectoryFilesRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(allDirectoryHierarchyFilesRadioButton)
                .addGap(5, 5, 5)
                .addComponent(batchFileRadioButton)
                .addGap(23, 23, 23)
                .addComponent(specifySourceFileStaticText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sourceCodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sourceCodeFileTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chooseFileOnDiscButton))
                .addContainerGap())
        );

        configurationTabbedPane.addTab("Sources", sourceCodePanel);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        checkersTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        checkersTree.setRootVisible(false);
        checkersTreeScrollPane.setViewportView(checkersTree);

        addCheckerButton.setText("Add Checker");

        removeCheckerButton.setText("Remove Checker");

        addDataButton.setText("Add Data");

        removeDataButton.setText("Remove Data");

        javax.swing.GroupLayout checkersPanelLayout = new javax.swing.GroupLayout(checkersPanel);
        checkersPanel.setLayout(checkersPanelLayout);
        checkersPanelLayout.setHorizontalGroup(
            checkersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addCheckerButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removeCheckerButton)
                .addGap(107, 107, 107)
                .addComponent(addDataButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removeDataButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(checkersTreeScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
        );
        checkersPanelLayout.setVerticalGroup(
            checkersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkersPanelLayout.createSequentialGroup()
                .addComponent(checkersTreeScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(checkersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addCheckerButton)
                    .addComponent(removeCheckerButton)
                    .addComponent(removeDataButton)
                    .addComponent(addDataButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        configurationTabbedPane.addTab("Checkers", checkersPanel);

        closeButton.setText("Close");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(configurationTabbedPane)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(464, Short.MAX_VALUE)
                .addComponent(closeButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(configurationTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        configurationTabbedPane.getAccessibleContext().setAccessibleName("Source code");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton actualOpenedFileRadioButton;
    private javax.swing.JButton addCheckerButton;
    private javax.swing.JButton addDataButton;
    private javax.swing.JRadioButton allDirectoryFilesRadioButton;
    private javax.swing.JRadioButton allDirectoryHierarchyFilesRadioButton;
    private javax.swing.JRadioButton allOpenedFilesRadioButton;
    private javax.swing.JRadioButton batchFileRadioButton;
    private javax.swing.JPanel checkersPanel;
    private javax.swing.JTree checkersTree;
    private javax.swing.JScrollPane checkersTreeScrollPane;
    private javax.swing.JButton chooseFileOnDiscButton;
    private javax.swing.JButton closeButton;
    private javax.swing.JTabbedPane configurationTabbedPane;
    private javax.swing.JRadioButton makefileRadioButton;
    private javax.swing.JButton removeCheckerButton;
    private javax.swing.JButton removeDataButton;
    private javax.swing.JTextPane selectTypeStaticText;
    private javax.swing.JRadioButton singleSourceFileRadioButton;
    private javax.swing.JTextField sourceCodeFileTextField;
    private javax.swing.JPanel sourceCodePanel;
    private javax.swing.ButtonGroup sourceTypeButtonGroup;
    private javax.swing.JTextPane specifySourceFileStaticText;
    // End of variables declaration//GEN-END:variables
    //
    // End --- section generated by NetBeans - do not modify ! ---
    //
}
