#!/bin/bash

CLASS=$1

cat >cparser/AST/$CLASS.java <<EOF
/*
 * Licensed under GPLv2
 */

package cparser.AST;

import java.util.HashMap;
import java.util.Map;

/**
 * @author Jiri Slaby
 */
public class $CLASS extends Node {

}
EOF

git add cparser/AST/$CLASS.java
