/*
 * Graph.java
 *
 * Created on 16. �erven 2006, 16:56
 */

package cz.muni.fi.iti.scv.scvgui;


import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 * Form for viewing graphs generated from dot source codes.
 * @author  xstastn
 */
public class GraphForm extends javax.swing.JFrame {
    
    
    /** Creates new form Graph */
    public GraphForm() {
        this.initComponents();
    }
    
    /**
     * Sets the image in the label
     * @param image Image to be set as the label
     */
    public void setImage (Icon image) {
        this.jLabel1.setIcon(image);
        this.jScrollPane1.setSize(image.getIconWidth(),image.getIconHeight());
        
    }
    
    
    /**
     * Zobrazi okno s grafem, ktery je definovan parametrem dotSource
     *
     * @param fileName      Jmeno docasneho souboru, pouzite pri vytvareni grafu
     * @param dotSource     Zdrojovy kod dot souboru, ke kteremu ma byt vykreslen graf
     *          
     */
    public GraphForm(String fileName, String dotSource) {
        
        
        GraphViz gv = new GraphViz();
        // uvodni zavorka
        gv.graph.append(dotSource);
       
        try {
            File out = File.createTempFile("SCVCallGraph",".png");
            out.deleteOnExit();
            gv.writeGraphToFile(gv.getGraph(gv.getDotSource()), out);
            
            this.initComponents();
            this.setTitle(fileName);
            this.setImage(new ImageIcon(out.getAbsolutePath()));
            this.setVisible(true);
        } catch (IOException ex) {
            ex.printStackTrace();
        }
          
    
    }

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CFG Graph");
        setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setName("graphImage");
        jScrollPane1.setViewportView(jLabel1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
        
        
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
}
